language: rust
env:
  global:
    - REPO=git-igitt

os:
  - linux
  - windows
  - osx

rust:
  - stable

branches:
  only:
    - master
    - "/^\\d+\\.\\d+\\.\\d+/"

script:
  - rustup component add rustfmt clippy
  - cargo fmt -- --check
  - cargo clippy --all-targets -- --deny warnings
  - cargo test --verbose

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry

before_deploy:
  - cargo build --release
  - rm -rf ${REPO} || exit 0
  - mkdir ${REPO}
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cp -f target/release/git-igitt ${REPO} > /dev/null; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cp -f target/release/git-igitt ${REPO} > /dev/null; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cp -f target/release/git-igitt.exe ${REPO} > /dev/null; fi
  - tar -czf ${REPO}-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.tar.gz ${REPO}

deploy:
  provider: releases
  skip_cleanup: true
  token:
    secure: VZeyaOjqDE7uqdQbgRRXBkmC2qMYos5p+g688VtPOicrjHQeGtwGzcNCj4FGXEWbBsBtIzBkto+YVKTsSf8aoMMwIe31HQSAr7Eh6RlRePugWriv8V7del6+Mz+SmeOJdg1Jptc0ikfJhIgtnSFingqN2HI4R8MI+zfV2i7XoFeDN+LCUTAlvOOmJCsdSRG0y1Mr+REiFEVet/IosGHgcYFjPfRavcMBj5edYvkXlkbcsAC0lpv75yp330XPmlqnIDtOd/wkEGFXNpzdGUcmZ9+syxLLmPvURG1vERFhHCjzz3QWeXj6nAxkU1vq3CnZB1KHHpe6fMbfghI5O/r4uSx61j6Z7f7iaAHmxo2D2xqtaFUUy/W+xRt20Wi4CrJ1wgX819hIV7hfQagDbe3wlALgLPizZiVD0GYm5YllfqKQvwmZRCaC7j9B/iqgeURPxM2WNk/B9qPh+pOdZIDk9rkTBNGp2iVkXAQmXqDQzs9QQjPDFOQiwn95qQciy/cJTlM89UC3p49yuBSRtsWH/a5JOHcPeM3NKmucA9UYxKXzf6gep2MCE9Ybx9AfpTLPxNE+UIKHaY9ENsfyxUqJkpUUppkex4N5FbkweHqU35k/r2AWjwVxJE0gp+a3b/Kx0sGlnIElrNcUo/HbWYKqX8ci5G9mA5tRknxfalUeEqY=
  file: ${REPO}-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.tar.gz
  on:
    tags: true
    all_branches: true
