[package]
name = "git-igitt"
version = "0.1.0"
authors = ["Martin Lange <martin_lange_@gmx.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["crossterm"]

[dependencies]
git2 = { version = "0.13", default-features = false, optional = false }
crossterm = { version = "0.19", optional = true }
tui = { version = "0.14", default-features = false, optional = false, features=["crossterm"] }
unicode-width = "0.1"
muncher = "0.6"
itertools = "0.10"
git-graph = { path = "../git-graph" }
